spring:
  application:
    name: E-Social
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: postgres